USE [master]
GO

/****** Object:  Database [CinemaOLTP]    Script Date: 03/12/2017 16:29:06 ******/
CREATE DATABASE [CinemaOLTP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CinemaOLTP', FILENAME = N'C:\CinemaOLTP\DB\MDF\CinemaOLTP.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CinemaOLTP_log', FILENAME = N'C:\CinemaOLTP\DB\LOG\CinemaOLTP_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CinemaOLTP] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CinemaOLTP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CinemaOLTP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CinemaOLTP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CinemaOLTP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CinemaOLTP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CinemaOLTP] SET ARITHABORT OFF 
GO

ALTER DATABASE [CinemaOLTP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CinemaOLTP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CinemaOLTP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CinemaOLTP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CinemaOLTP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CinemaOLTP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CinemaOLTP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CinemaOLTP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CinemaOLTP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CinemaOLTP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CinemaOLTP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CinemaOLTP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CinemaOLTP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CinemaOLTP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CinemaOLTP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CinemaOLTP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CinemaOLTP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CinemaOLTP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CinemaOLTP] SET  MULTI_USER 
GO

ALTER DATABASE [CinemaOLTP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CinemaOLTP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CinemaOLTP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CinemaOLTP] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CinemaOLTP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CinemaOLTP] SET  READ_WRITE 
GO


