USE [master]
GO

/****** Object:  Database [CinemaDW]    Script Date: 03/12/2017 19:36:48 ******/
CREATE DATABASE [CinemaDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CinemaDW_Data', FILENAME = N'C:\CinemaDW\DB\MDF\CinemaDW_Data.MDF' , SIZE = 39488KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'CinemaDW_Log', FILENAME = N'C:\CinemaDW\DB\LOG\CinemaDW_Log.LDF' , SIZE = 32448KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CinemaDW] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CinemaDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CinemaDW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CinemaDW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CinemaDW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CinemaDW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CinemaDW] SET ARITHABORT OFF 
GO

ALTER DATABASE [CinemaDW] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CinemaDW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CinemaDW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CinemaDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CinemaDW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CinemaDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CinemaDW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CinemaDW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CinemaDW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CinemaDW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CinemaDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CinemaDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CinemaDW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CinemaDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CinemaDW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CinemaDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CinemaDW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CinemaDW] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CinemaDW] SET  MULTI_USER 
GO

ALTER DATABASE [CinemaDW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CinemaDW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CinemaDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CinemaDW] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CinemaDW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CinemaDW] SET  READ_WRITE 
GO


